=== Nuvoton-Israel/facebook-openbmc/common/recipes-core/rackmon2/rackmon/schemas/RegisterMapConfigSchema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "regmap",
  "title": "Rackmon Register Map Configuration",
  "description": "Schema to test the Register Map JSON configuration",
  "type": "object",
  "required": ["name", "address_range", "probe_register", "baudrate", "registers"],
  "additionalProperties": false,
  
  "properties": {
    "name": {
      "type": "string"
    },
    "address_range": {
      "type": "array",
      "minItems": 1,
      "maxItems": 256,
      "items": {
        "type": "array",
        "minItems": 2,
        "maxItems": 2,
        "items": {
          "type": "integer",
          "minimum": 0,
          "maximum": 255
        }
      }
    },
    "probe_register": {
      "type": "integer",
      "minimum": 0,
      "maximum": 65535
    },
    "baudrate": {
      "type": "integer",
      "minimum": 19200,
      "maximum": 115200
    },
    "max_span_length": {
      "type": "integer",
      "minimum": 1,
      "maximum": 120
    },
    "parity": {
      "type": "string",
      "enum": ["EVEN", "ODD", "NONE"]
    },
    "registers": {
      "type": "array",
      "minItems": 1,
      "maxItems": 65536,
      "items": {
        "$ref": "registermap/register.json#/definitions"
      }
    },
    "special_handlers": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "registermap/special_handlers.json#/definitions"
      }
    }
  }
}

=== Nuvoton-Israel/facebook-openbmc/common/recipes-core/rackmon2/rackmon/configs/register_map/orv3_rpu.json
{
    "name": "ORV3_RPU",
    "address_range": [
        [
            12,
            12
        ]
    ],
    "probe_register": 36864,
    "baudrate": 19200,
    "parity": "NONE",
    "registers": [
        {
            "begin": 6561,
            "length": 1,
            "format": "INTEGER",
            "name": "Sticky_IT_RPU_Stop_Pump_0"
        },
        {
            "begin": 6562,
            "length": 1,
            "format": "INTEGER",
            "name": "Sticky_IT_RPU_Stop_Pump_1"
        },
        {
            "begin": 6563,
            "length": 1,
            "format": "INTEGER",
            "name": "Sticky_IT_RPU_Stop_Pump_2"
        },
        {
            "begin": 6564,
            "length": 1,
            "format": "INTEGER",
            "name": "Sticky_IT_RPU_Stop_Pump_3"
        },
        {
            "begin": 6565,
            "length": 1,
            "format": "INTEGER",
            "name": "Sticky_RPU_Internal_Leakage_Abnormal"
        },
        {
            "begin": 6566,
            "length": 1,
            "format": "INTEGER",
            "name": "Sticky_RPU_External_Leakage_Abnormal"
        },
        {
            "begin": 6567,
            "length": 1,
            "format": "INTEGER",
            "name": "Sticky_RPU_Opt_External_Leakage1_Abnormal"
        },
        {
            "begin": 6568,
            "length": 1,
            "format": "INTEGER",
            "name": "Sticky_RPU_Opt_External_Leakage2_Abnormal"
        },
        {
            "begin": 6569,
            "length": 1,
            "format": "INTEGER",
            "name": "Sticky_HEX_Rack_Pan_Leakage"
        },
        {
            "begin": 6570,
            "length": 1,
            "format": "INTEGER",
            "name": "Sticky_HEX_Rack_Floor_Leakage"
        },
        {
            "begin": 6571,
            "length": 1,
            "format": "INTEGER",
            "name": "Sticky_HEX_Rack_Pan_Leakage_Relay"
        },
        {
            "begin": 6572,
            "length": 1,
            "format": "INTEGER",
            "name": "Sticky_HEX_Rack_Floor_Leakage_Relay"
        },
        {
            "begin": 6596,
            "length": 8,
            "format": "STRING",
            "name": "RPU_FBPN"
        },
        {
            "begin": 6604,
            "length": 8,
            "format": "STRING",
            "name": "RPU_MFR_Model"
        },
        {
            "begin": 6612,
            "length": 4,
            "format": "STRING",
            "name": "RPU_MFR_Date"
        },
        {
            "begin": 6616,
            "length": 8,
            "format": "STRING",
            "name": "RPU_MFR_Serial"
        },
        {
            "begin": 6624,
            "length": 4,
            "format": "STRING",
            "name": "RPU_Workorder"
        },
        {
            "begin": 6628,
            "length": 4,
            "format": "STRING",
            "name": "RPU_HW_Revision"
        },
        {
            "begin": 6632,
            "length": 4,
            "format": "STRING",
            "name": "RPU_PLC_FW_Revision"
        },
        {
            "begin": 6642,
            "length": 4,
            "format": "STRING",
            "name": "RPU_HMI_FW_Revision"
        },
        {
            "begin": 6646,
            "length": 2,
            "format": "STRING",
            "name": "RPU_HEX_FW_Revision"
        },
        {
            "begin": 6648,
            "length": 4,
            "format": "STRING",
            "name": "RPU_Noahs_Ark_Configuration"
        },
        {
            "begin": 6652,
            "length": 4,
            "format": "STRING",
            "name": "RPU_Reservoir_And_Pumping_Unit_FBPN"
        },
        {
            "begin": 6656,
            "length": 4,
            "format": "STRING",
            "name": "Heat_Exchanger_Control_Box_FBPN"
        },
        {
            "begin": 6660,
            "length": 4,
            "format": "STRING",
            "name": "Heat_Exchanger_Fans_FBPN"
        },
        {
            "begin": 6664,
            "length": 4,
            "format": "STRING",
            "name": "Heat_Exchanger_Fan_Control_Box_FBPN"
        },
        {
            "begin": 6636,
            "length": 2,
            "format": "INTEGER",
            "name": "Total_Up_Time"
        },
        {
            "begin": 6639,
            "length": 2,
            "format": "INTEGER",
            "name": "Time_Since_Last_On"
        },
        {
            "begin": 36864,
            "length": 1,
            "format": "FLOAT",
            "precision": 0,
            "scale": 0.1,
            "name": "RPU_Coolant_Flow_Rate_LPM"
        },
        {
            "begin": 36865,
            "length": 1,
            "format": "FLOAT",
            "precision": 0,
            "scale": 0.1,
            "name": "RPU_Coolant_Outlet_Temp_C"
        },
        {
            "begin": 36866,
            "length": 1,
            "format": "FLOAT",
            "precision": 0,
            "scale": 0.1,
            "name": "RPU_Coolant_Inlet_Temp_C"
        },
        {
            "begin": 36867,
            "length": 1,
            "format": "FLOAT",
            "precision": 0,
            "sign": true,
            "scale": 0.1,
            "name": "RPU_Coolant_Outlet_Pressure_kPa"
        },
        {
            "begin": 36868,
            "length": 1,
            "format": "FLOAT",
            "precision": 0,
            "sign": true,
            "scale": 0.1,
            "name": "RPU_Coolant_Inlet_Pressure_kPa"
        },
        {
            "begin": 36869,
            "length": 1,
            "format": "FLOAT",
            "precision": 0,
            "scale": 0.1,
            "name": "RPU_Power_W"
        },
        {
            "begin": 36870,
            "length": 1,
            "format": "FLOAT",
            "precision": 0,
            "name": "AALC_Total_Power_W"
        },
        {
            "begin": 36871,
            "length": 1,
            "format": "FLOAT",
            "precision": 0,
            "scale": 0.1,
            "name": "RPU_Input_Volt_V"
        },
        {
            "begin": 36872,
            "length": 1,
            "format": "FLOAT",
            "precision": 0,
            "scale": 0.1,
            "name": "RPU_Air_Inlet_Temp_C"
        },
        {
            "begin": 36873,
            "length": 1,
            "format": "INTEGER",
            "name": "RPU_Pump_PWM_Pct"
        },
        {
            "begin": 36874,
            "length": 1,
            "format": "INTEGER",
            "name": "RPU_Pump1_TACH_RPM"
        },
        {
            "begin": 36875,
            "length": 1,
            "format": "INTEGER",
            "name": "RPU_Pump2_TACH_RPM"
        },
        {
            "begin": 36876,
            "length": 1,
            "format": "INTEGER",
            "name": "RPU_Pump3_TACH_RPM"
        },
        {
            "begin": 36877,
            "length": 1,
            "format": "INTEGER",
            "name": "RPU_Pump4_TACH_RPM"
        },
        {
            "begin": 36878,
            "length": 1,
            "format": "FLAGS",
            "flags": [
                [
                    1,
                    "RPU_Fan2_Status"
                ],
                [
                    0,
                    "RPU_Fan1_Status"
                ]
            ],
            "name": "RPU_Fan_Status"
        },
        {
            "begin": 36879,
            "length": 1,
            "format": "INTEGER",
            "name": "RPU_Fan1_TACH_RPM"
        },
        {
            "begin": 36880,
            "length": 1,
            "format": "INTEGER",
            "name": "RPU_Fan2_TACH_RPM"
        },
        {
            "begin": 36881,
            "length": 1,
            "format": "FLOAT",
            "precision": 0,
            "scale": 0.1,
            "name": "AALC_Cooling_Capacity_W"
        },
        {
            "begin": 36882,
            "length": 1,
            "format": "INTEGER",
            "name": "RPU_Pump1_Status"
        },
        {
            "begin": 36883,
            "length": 1,
            "format": "INTEGER",
            "name": "RPU_Pump2_Status"
        },
        {
            "begin": 36884,
            "length": 1,
            "format": "INTEGER",
            "name": "RPU_Pump3_Status"
        },
        {
            "begin": 36885,
            "length": 1,
            "format": "INTEGER",
            "name": "RPU_Pump4_Status"
        },
        {
            "begin": 36886,
            "length": 1,
            "format": "INTEGER",
            "name": "RPU_Reservoir_Status"
        },
        {
            "begin": 36887,
            "length": 1,
            "format": "FLAGS",
            "flags": [
                [
                    4,
                    "RPU_LED_Power_Status"
                ],
                [
                    3,
                    "RPU_LED_Fault_Status"
                ],
                [
                    2,
                    "RPU_LED_Leakage_Status"
                ],
                [
                    1,
                    "RPU_LED_Reservoir_Blinking"
                ],
                [
                    0,
                    "RPU_LED_Reservoir_On"
                ]
            ],
            "name": "RPU_LED_Status"
        },
        {
            "begin": 36888,
            "length": 1,
            "format": "INTEGER",
            "name": "RPU_Pump_Status"
        },
        {
            "begin": 36889,
            "length": 1,
            "format": "INTEGER",
            "name": "RPU_Internal_Fan_Status"
        },
        {
            "begin": 36912,
            "length": 2,
            "format": "INTEGER",
            "name": "RPU_Pump1_Runtime"
        },
        {
            "begin": 36914,
            "length": 2,
            "format": "INTEGER",
            "name": "RPU_Pump2_Runtime"
        },
